pipeline:
  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      debug: true
      repo: git.cyberia.club/${CI_REPO_OWNER}/reticule
      tag: latest
      registry: https://index.docker.io/v1/
      username: reeseovine
      password:
        from_secret: DOCKERHUB_TOKEN
    when:
      event: push
      branch: ${CI_REPO_DEFAULT_BRANCH}
